version: '3.4'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: on-failure:2
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
